before:
  hooks:
    - go mod download
builds:
  -
    main: ./cmd/main.go
    binary: go-bpkg
    ldflags:
      -X "{{.Env.KITPACKAGE}}/cmd/cobra/version.Version={{.Tag}}" -X "{{.Env.KITPACKAGE}}/cmd/cobra/version.Revision={{.Env.REV}}" -X "{{.Env.KITPACKAGE}}/cmd/cobra/version.Branch={{.Env.BRANCH}}" -X "{{.Env.KITPACKAGE}}/cmd/cobra/version.BuildDate={{.Env.BUILDDATE}}" -X "{{.Env.KITPACKAGE}}/cmd/cobra/version.GoVersion={{.Env.GOVERSION}}"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
dockers:
  - image_templates:
      - "rafaelcalleja/go-bpkg:latest"
      - "rafaelcalleja/go-bpkg:{{ .Version }}"
      - "rafaelcalleja/go-bpkg:{{ .Version }}-amd64"
    use: buildx
    dockerfile: "GoReleaser.Dockerfile"
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "rafaelcalleja/go-bpkg:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: "GoReleaser.Dockerfile"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: rafaelcalleja/go-bpkg:{{ .Version }}
    image_templates:
      - rafaelcalleja/go-bpkg:{{ .Version }}-amd64
      - rafaelcalleja/go-bpkg:{{ .Version }}-arm64v8
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
